[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-openai",
    "build-cohere",
    "build-hugging-face",
    "build-voyageai",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-openai",
    "release-build-cohere",
    "release-build-hugging-face",
    "release-build-voyageai",
] }

[tasks.build-openai]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-openai"]

[tasks.build-cohere]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-cohere"]

[tasks.build-hugging-face]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-hugging-face"]

[tasks.build-voyageai]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-voyageai"]

[tasks.release-build-openai]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-openai", "--release"]

[tasks.release-build-cohere]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-cohere", "--release"]

[tasks.release-build-hugging-face]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-hugging-face", "--release"]

[tasks.release-build-voyageai]
command = "cargo"
args = ["build", "-p", "golem-ai-embed-voyageai", "--release"]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds embed test components with golem-cli"
script = '''
cd ../test/embed

golem-cli --version
golem-cli clean
golem-cli build --preset openai-debug
golem-cli clean
golem-cli build --preset cohere-debug
golem-cli clean
golem-cli build --preset hugging-face-debug
golem-cli clean
golem-cli build --preset voyageai-debug
'''
