use golem_stt::golem::stt::languages::{Guest as LanguagesGuest, LanguageInfo};
use golem_stt::golem::stt::types::SttError;

const LANGUAGES: &[(&str, &str, &str)] = &[
    ("af-ZA", "Afrikaans (South Africa)", "Afrikaans (South Africa)"),
    ("am-ET", "Amharic (Ethiopia)", "Amharic (Ethiopia)"),
    ("ar-AE", "Arabic (United Arab Emirates)", "العربية (الإمارات)"),
    ("ar-BH", "Arabic (Bahrain)", "العربية (البحرين)"),
    ("ar-DZ", "Arabic (Algeria)", "العربية (الجزائر)"),
    ("ar-EG", "Arabic (Egypt)", "العربية (مصر)"),
    ("ar-IL", "Arabic (Israel)", "العربية (إسرائيل)"),
    ("ar-IQ", "Arabic (Iraq)", "العربية (العراق)"),
    ("ar-JO", "Arabic (Jordan)", "العربية (الأردن)"),
    ("ar-KW", "Arabic (Kuwait)", "العربية (الكويت)"),
    ("ar-LB", "Arabic (Lebanon)", "العربية (لبنان)"),
    ("ar-LY", "Arabic (Libya)", "العربية (ليبيا)"),
    ("ar-MA", "Arabic (Morocco)", "العربية (المغرب)"),
    ("ar-OM", "Arabic (Oman)", "العربية (عُمان)"),
    ("ar-PS", "Arabic (Palestinian Authority)", "العربية (فلسطين)"),
    ("ar-QA", "Arabic (Qatar)", "العربية (قطر)"),
    ("ar-SA", "Arabic (Saudi Arabia)", "العربية (السعودية)"),
    ("ar-SY", "Arabic (Syria)", "العربية (سوريا)"),
    ("ar-TN", "Arabic (Tunisia)", "العربية (تونس)"),
    ("ar-YE", "Arabic (Yemen)", "العربية (اليمن)"),
    ("as-IN", "Assamese (India)", "অসমীয়া (ভাৰত)"),
    ("az-AZ", "Azerbaijani (Latin, Azerbaijan)", "Azərbaycan (Latın, Azərbaycan)"),
    ("bg-BG", "Bulgarian (Bulgaria)", "Български (България)"),
    ("bn-IN", "Bengali (India)", "বাংলা (ভারত)"),
    ("bs-BA", "Bosnian (Bosnia and Herzegovina)", "Bosanski (Bosna i Hercegovina)"),
    ("ca-ES", "Catalan", "Català"),
    ("cs-CZ", "Czech (Czechia)", "Čeština (Česko)"),
    ("cy-GB", "Welsh (United Kingdom)", "Cymraeg (Y Deyrnas Unedig)"),
    ("da-DK", "Danish (Denmark)", "Dansk (Danmark)"),
    ("de-AT", "German (Austria)", "Deutsch (Österreich)"),
    ("de-CH", "German (Switzerland)", "Deutsch (Schweiz)"),
    ("de-DE", "German (Germany)", "Deutsch (Deutschland)"),
    ("el-GR", "Greek (Greece)", "Ελληνικά (Ελλάδα)"),
    ("en-AU", "English (Australia)", "English (Australia)"),
    ("en-CA", "English (Canada)", "English (Canada)"),
    ("en-GB", "English (United Kingdom)", "English (United Kingdom)"),
    ("en-GH", "English (Ghana)", "English (Ghana)"),
    ("en-HK", "English (Hong Kong SAR)", "English (Hong Kong SAR)"),
    ("en-IE", "English (Ireland)", "English (Ireland)"),
    ("en-IN", "English (India)", "English (India)"),
    ("en-KE", "English (Kenya)", "English (Kenya)"),
    ("en-NG", "English (Nigeria)", "English (Nigeria)"),
    ("en-NZ", "English (New Zealand)", "English (New Zealand)"),
    ("en-PH", "English (Philippines)", "English (Philippines)"),
    ("en-SG", "English (Singapore)", "English (Singapore)"),
    ("en-TZ", "English (Tanzania)", "English (Tanzania)"),
    ("en-US", "English (United States)", "English (United States)"),
    ("en-ZA", "English (South Africa)", "English (South Africa)"),
    ("es-AR", "Spanish (Argentina)", "Español (Argentina)"),
    ("es-BO", "Spanish (Bolivia)", "Español (Bolivia)"),
    ("es-CL", "Spanish (Chile)", "Español (Chile)"),
    ("es-CO", "Spanish (Colombia)", "Español (Colombia)"),
    ("es-CR", "Spanish (Costa Rica)", "Español (Costa Rica)"),
    ("es-CU", "Spanish (Cuba)", "Español (Cuba)"),
    ("es-DO", "Spanish (Dominican Republic)", "Español (República Dominicana)"),
    ("es-EC", "Spanish (Ecuador)", "Español (Ecuador)"),
    ("es-ES", "Spanish (Spain)", "Español (España)"),
    ("es-GQ", "Spanish (Equatorial Guinea)", "Español (Guinea Ecuatorial)"),
    ("es-GT", "Spanish (Guatemala)", "Español (Guatemala)"),
    ("es-HN", "Spanish (Honduras)", "Español (Honduras)"),
    ("es-MX", "Spanish (Mexico)", "Español (México)"),
    ("es-NI", "Spanish (Nicaragua)", "Español (Nicaragua)"),
    ("es-PA", "Spanish (Panama)", "Español (Panamá)"),
    ("es-PE", "Spanish (Peru)", "Español (Perú)"),
    ("es-PR", "Spanish (Puerto Rico)", "Español (Puerto Rico)"),
    ("es-PY", "Spanish (Paraguay)", "Español (Paraguay)"),
    ("es-SV", "Spanish (El Salvador)", "Español (El Salvador)"),
    ("es-US", "Spanish (United States)", "Español (Estados Unidos)"),
    ("es-UY", "Spanish (Uruguay)", "Español (Uruguay)"),
    ("es-VE", "Spanish (Venezuela)", "Español (Venezuela)"),
    ("et-EE", "Estonian (Estonia)", "Eesti (Eesti)"),
    ("eu-ES", "Basque", "Euskara"),
    ("fa-IR", "Persian (Iran)", "فارسی (ایران)"),
    ("fi-FI", "Finnish (Finland)", "Suomi (Suomi)"),
    ("fil-PH", "Filipino (Philippines)", "Filipino (Pilipinas)"),
    ("fr-BE", "French (Belgium)", "Français (Belgique)"),
    ("fr-CA", "French (Canada)", "Français (Canada)"),
    ("fr-CH", "French (Switzerland)", "Français (Suisse)"),
    ("fr-FR", "French (France)", "Français (France)"),
    ("ga-IE", "Irish (Ireland)", "Gaeilge (Éire)"),
    ("gl-ES", "Galician", "Galego"),
    ("gu-IN", "Gujarati (India)", "ગુજરાતી (ભારત)"),
    ("he-IL", "Hebrew (Israel)", "עברית (ישראל)"),
    ("hi-IN", "Hindi (India)", "हिन्दी (भारत)"),
    ("hr-HR", "Croatian (Croatia)", "Hrvatski (Hrvatska)"),
    ("hu-HU", "Hungarian (Hungary)", "Magyar (Magyarország)"),
    ("hy-AM", "Armenian (Armenia)", "Հայերեն (Հայաստան)"),
    ("id-ID", "Indonesian (Indonesia)", "Bahasa Indonesia (Indonesia)"),
    ("is-IS", "Icelandic (Iceland)", "Íslenska (Ísland)"),
    ("it-CH", "Italian (Switzerland)", "Italiano (Svizzera)"),
    ("it-IT", "Italian (Italy)", "Italiano (Italia)"),
    ("ja-JP", "Japanese (Japan)", "日本語 (日本)"),
    ("jv-ID", "Javanese (Latin, Indonesia)", "Basa Jawa (Latin, Indonesia)"),
    ("ka-GE", "Georgian (Georgia)", "ქართული (საქართველო)"),
    ("kk-KZ", "Kazakh (Kazakhstan)", "Қазақ (Қазақстан)"),
    ("km-KH", "Khmer (Cambodia)", "ភាសាខ្មែរ (កម្ពុជា)"),
    ("kn-IN", "Kannada (India)", "ಕನ್ನಡ (ಭಾರತ)"),
    ("ko-KR", "Korean (Korea)", "한국어 (대한민국)"),
    ("lo-LA", "Lao (Laos)", "ລາວ (ສ.ປ.ປ ລາວ)"),
    ("lt-LT", "Lithuanian (Lithuania)", "Lietuvių (Lietuva)"),
    ("lv-LV", "Latvian (Latvia)", "Latviešu (Latvija)"),
    ("mk-MK", "Macedonian (North Macedonia)", "Македонски (Северна Македонија)"),
    ("ml-IN", "Malayalam (India)", "മലയാളം (ഇന്ത്യ)"),
    ("mn-MN", "Mongolian (Mongolia)", "Монгол (Монгол)"),
    ("mr-IN", "Marathi (India)", "मराठी (भारत)"),
    ("ms-MY", "Malay (Malaysia)", "Bahasa Melayu (Malaysia)"),
    ("mt-MT", "Maltese (Malta)", "Malti (Malta)"),
    ("my-MM", "Burmese (Myanmar)", "မြန်မာ (မြန်မာ)"),
    ("nb-NO", "Norwegian Bokmål (Norway)", "Norsk bokmål (Norge)"),
    ("ne-NP", "Nepali (Nepal)", "नेपाली (नेपाल)"),
    ("nl-BE", "Dutch (Belgium)", "Nederlands (België)"),
    ("nl-NL", "Dutch (Netherlands)", "Nederlands (Nederland)"),
    ("or-IN", "Odia (India)", "ଓଡ଼ିଆ (ଭାରତ)"),
    ("pa-IN", "Punjabi (India)", "ਪੰਜਾਬੀ (ਭਾਰਤ)"),
    ("pl-PL", "Polish (Poland)", "Polski (Polska)"),
    ("ps-AF", "Pashto (Afghanistan)", "پښتو (افغانستان)"),
    ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)"),
    ("pt-PT", "Portuguese (Portugal)", "Português (Portugal)"),
    ("ro-RO", "Romanian (Romania)", "Română (România)"),
    ("ru-RU", "Russian (Russia)", "Русский (Россия)"),
    ("si-LK", "Sinhala (Sri Lanka)", "සිංහල (ශ්‍රී ලංකා)"),
    ("sk-SK", "Slovak (Slovakia)", "Slovenčina (Slovensko)"),
    ("sl-SI", "Slovenian (Slovenia)", "Slovenščina (Slovenija)"),
    ("so-SO", "Somali (Somalia)", "Af Soomaali (Soomaaliya)"),
    ("sq-AL", "Albanian (Albania)", "Shqip (Shqipëri)"),
    ("sv-SE", "Swedish (Sweden)", "Svenska (Sverige)"),
    ("sw-KE", "Kiswahili (Kenya)", "Kiswahili (Kenya)"),
    ("sw-TZ", "Kiswahili (Tanzania)", "Kiswahili (Tanzania)"),
    ("ta-IN", "Tamil (India)", "தமிழ் (இந்தியா)"),
    ("te-IN", "Telugu (India)", "తెలుగు (భారతదేశం)"),
    ("th-TH", "Thai (Thailand)", "ไทย (ประเทศไทย)"),
    ("tr-TR", "Turkish (Türkiye)", "Türkçe (Türkiye)"),
    ("uk-UA", "Ukrainian (Ukraine)", "Українська (Україна)"),
    ("ur-IN", "Urdu (India)", "اُردو (بھارت)"),
    ("uz-UZ", "Uzbek (Latin, Uzbekistan)", "O‘zbek (Lotin, O‘zbekiston)"),
    ("vi-VN", "Vietnamese (Vietnam)", "Tiếng Việt (Việt Nam)"),
    ("yue-CN", "Chinese (Cantonese, Simplified)", "粤语 (简体)"),
    ("zh-CN", "Chinese (Mandarin, Simplified)", "中文 (简体)"),
    ("zh-HK", "Chinese (Cantonese, Traditional)", "中文 (香港)"),
    ("zh-TW", "Chinese (Taiwanese Mandarin, Traditional)", "中文 (繁體)"),
];

pub struct AzureLanguagesComponent;

impl LanguagesGuest for AzureLanguagesComponent {
    fn list_languages() -> Result<Vec<LanguageInfo>, SttError> {
        Ok(LANGUAGES
            .iter()
            .map(|(code, name, native)| LanguageInfo {
                code: (*code).into(),
                name: (*name).into(),
                native_name: (*native).into(),
            })
            .collect())
    }
}