[workspace]
resolver = "2"

members = [
    "llm/llm",
    "llm/bedrock",
    "llm/anthropic",
    "llm/grok",
    "llm/ollama",
    "llm/openai",
    "llm/openrouter",
    "websearch/websearch",
    "websearch/brave",
    "websearch/google",
    "websearch/serper",
    "websearch/tavily",
    "search/search",
    "search/elasticsearch",
    "search/algolia",
    "search/meilisearch",
    "search/opensearch",
    "search/typesense", 
    "graph/graph",
    "graph/neo4j",
    "graph/arangodb",
    "graph/janusgraph"

    "video/video",
    "video/kling",
    "video/runway",
    "video/veo",
    "video/stability",
]

[profile.release]
debug = false
lto = true
opt-level = 's'

[workspace.dependencies]
golem-llm = { path = "llm/llm", version = "0.0.0", default-features = false }
golem-search = { path = "search/search", version = "0.0.0", default-features = false}
golem-video = { path = "video/video", version = "0.0.0", default-features = false}
golem-rust = "1.6.0"
log = "0.4.27"
reqwest = { git = "https://github.com/golemcloud/reqwest", branch = "update-may-2025", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }
base64 = { version = "0.22.1" }