[workspace]
resolver = "2"

members = [ 
    "golem-embed/embed", 
    "golem-embed/embed-openai", 
    "golem-llm/llm", 
    "golem-llm/llm-anthropic",
    "golem-llm/llm-grok", 
    "golem-llm/llm-ollama",
    "golem-llm/llm-openai", 
    "golem-llm/llm-openrouter"  
]

[profile.release]
debug = false
lto = true
opt-level = 's'

[workspace.dependencies]
golem-rust = "1.6.0"
log = "0.4.27"
reqwest = { git = "https://github.com/golemcloud/reqwest", branch = "update-may-2025", features = [
    "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }
base64 = { version = "0.22.1" }
