[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-javascript",
    "build-python",
    "build-full"
] }

[tasks.release-build]
run_task = { name = [
    "release-build-full",
] }

[tasks.build-javascript]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec --no-default-features --features javascript --features durability
'''

[tasks.build-python]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec --no-default-features --features python --features durability
'''

[tasks.build-full]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec
'''

[tasks.release-build-javascript]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec --release --no-default-features --features javascript --features durability
'''

[tasks.release-build-python]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec --release --no-default-features --features python --features durability
'''

[tasks.release-build-full]
script_runner = "@duckscript"
script = '''
exec cargo build -p golem-ai-exec --release
'''

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds exec test components with golem-cli"
script = '''
cd ../test/exec

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds exec test components with golem-cli"
script = '''
cd ../test/exec

golem-cli --version
golem-cli --dev-mode --preset release clean
golem-cli --dev-mode --preset release build
'''
