[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-algolia",
] }

[tasks.build-portable]
run_task = { name = [
    "build-algolia-portable",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-algolia",
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-algolia-portable",
] }

[tasks.build-algolia]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-search-algolia"]


[tasks.build-algolia-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-search-algolia", "--no-default-features"]


[tasks.release-build-algolia]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-search-algolia", "--release"]

[tasks.release-build-algolia-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-search-algolia", "--release", "--no-default-features"]

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]

script_runner = "@duckscript"
script = """
modules = array search algolia

for module in ${modules}
    rm -r ${module}/wit/deps
    mkdir ${module}/wit/deps/golem-search
    cp wit/golem-search.wit ${module}/wit/deps/golem-search/golem-search.wit
    cp wit/deps/wasi:io ${module}/wit/deps

    echo "Copied WIT for module search::${module}"
end

# Copy WIT files for integration tests
rm -r ../test/wit
mkdir ../test/wit/deps/golem-search
mkdir ../test/wit/deps/io
cp wit/golem-search.wit ../test/wit/deps/golem-search/golem-search.wit
cp wit/deps/wasi:io/error.wit ../test/wit/deps/io/error.wit
cp wit/deps/wasi:io/poll.wit ../test/wit/deps/io/poll.wit
cp wit/deps/wasi:io/streams.wit ../test/wit/deps/io/streams.wit
cp wit/deps/wasi:io/world.wit ../test/wit/deps/io/world.wit

echo "Copied WIT for module test"
"""

[tasks.build-test-components]
dependencies = ["build"]
install_crate = "cargo-binstall"
description = "Builds search test components with golem-cli"
script = '''
cargo-binstall golem-cli@1.2.2-dev.11 --locked --no-confirm
cargo-binstall wac-cli --locked --no-confirm
cd ../test

golem-cli --version
golem-cli app clean
golem-cli app build -b algolia-debug
'''
