[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-anthropic",
    "build-bedrock",
    "build-grok",
    "build-openai",
    "build-openrouter",
    "build-ollama",
] }

[tasks.build-portable]
run_task = { name = [
    "build-anthropic-portable",
    "build-bedrock-portable",
    "build-grok-portable",
    "build-openai-portable",
    "build-openrouter-portable",
    "build-ollama-portable",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-anthropic",
    "release-build-bedrock",
    "release-build-grok",
    "release-build-openai",
    "release-build-openrouter",
    "release-build-ollama",
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-anthropic-portable",
    "release-build-bedrock-portable",
    "release-build-grok-portable",
    "release-build-openai-portable",
    "release-build-openrouter-portable",
    "release-build-ollama-portable",
] }

[tasks.build-ollama]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-ollama"]


[tasks.build-ollama-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-ollama", "--no-default-features"]

[tasks.build-bedrock]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-bedrock"]


[tasks.build-bedrock-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-bedrock", "--no-default-features"]


[tasks.build-anthropic]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-anthropic"]

[tasks.build-anthropic-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-anthropic", "--no-default-features"]

[tasks.build-grok]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-grok"]

[tasks.build-grok-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-grok", "--no-default-features"]

[tasks.build-openai]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openai"]

[tasks.build-openai-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openai", "--no-default-features"]

[tasks.build-openrouter]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openrouter"]

[tasks.build-openrouter-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openrouter", "--no-default-features"]

[tasks.release-build-ollama]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-ollama", "--release"]

[tasks.release-build-ollama-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-ollama", "--release", "--no-default-features"]

[tasks.release-build-bedrock]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-bedrock", "--release"]

[tasks.release-build-bedrock-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-ai-llm-bedrock",
    "--release",
    "--no-default-features",
]

[tasks.release-build-anthropic]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-anthropic", "--release"]

[tasks.release-build-anthropic-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-ai-llm-anthropic",
    "--release",
    "--no-default-features",
]

[tasks.release-build-grok]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-grok", "--release"]

[tasks.release-build-grok-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-grok", "--release", "--no-default-features"]

[tasks.release-build-openai]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openai", "--release"]

[tasks.release-build-openai-portable]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openai", "--release", "--no-default-features"]

[tasks.release-build-openrouter]
command = "cargo"
args = ["build", "-p", "golem-ai-llm-openrouter", "--release"]

[tasks.release-build-openrouter-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-ai-llm-openrouter",
    "--release",
    "--no-default-features",
]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds llm test components with golem-cli"
script = '''
cd ../test/llm

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset anthropic-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset grok-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset openai-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset openrouter-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset ollama-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset bedrock-debug
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds llm test components with golem-cli"
script = '''
cd ../test/llm

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset anthropic-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset grok-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset openai-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset openrouter-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset ollama-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset bedrock-release
'''
