use crate::ChatStreamInterface;

/// Roles of the conversation
#[repr(u8)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    golem_rust::FromValueAndType,
    golem_rust::IntoValue,
)]
pub enum Role {
    /// Instructions provided by the user
    User,
    /// Messages generated by the model
    Assistant,
    /// Messages describing the system's rules
    System,
    /// Messages describing tool calls
    Tool,
}

/// Possible error cases for LLM calls
#[repr(u8)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    golem_rust::FromValueAndType,
    golem_rust::IntoValue,
)]
pub enum ErrorCode {
    /// Invalid request parameters
    InvalidRequest,
    /// Authentication failed
    AuthenticationFailed,
    /// Rate limit exceeded
    RateLimitExceeded,
    /// Internal error
    InternalError,
    /// Unsupported operation
    Unsupported,
    /// Unknown error
    Unknown,
}

/// Reasons for finishing a conversation
#[repr(u8)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    golem_rust::FromValueAndType,
    golem_rust::IntoValue,
)]
pub enum FinishReason {
    /// The conversation finished
    Stop,
    /// Conversation finished because of reaching the maximum length
    Length,
    /// Conversation finished with request for calling tools
    ToolCalls,
    /// Conversation finished because of content filtering
    ContentFilter,
    /// Conversation finished with an error
    Error,
    /// Other reason
    Other,
}

/// Image detail levels
#[repr(u8)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    golem_rust::FromValueAndType,
    golem_rust::IntoValue,
)]
pub enum ImageDetail {
    Low,
    High,
    Auto,
}

/// Points to an image by an URL and an optional image detail level
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ImageUrl {
    /// The URL of the image
    pub url: String,
    /// Level of detail of the image
    pub detail: Option<ImageDetail>,
}

/// Contains an inline image
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ImageSource {
    /// Raw image data
    pub data: Vec<u8>,
    /// MIME type of the image
    pub mime_type: String,
    /// Level of detail of the image
    pub detail: Option<ImageDetail>,
}

/// Contains an image, either a remote or an inlined one
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub enum ImageReference {
    /// A remote image
    Url(ImageUrl),
    /// An inlined image
    Inline(ImageSource),
}

/// One part of the conversation
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub enum ContentPart {
    /// Text content
    Text(String),
    /// Image content
    Image(ImageReference),
}

/// A message in the conversation
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Message {
    /// Role of this message
    pub role: Role,
    /// Name of the sender
    pub name: Option<String>,
    /// Content of the message
    pub content: Vec<ContentPart>,
}

/// Describes a tool callable by the LLM
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ToolDefinition {
    /// Name of the tool
    pub name: String,
    /// Description of the tool
    pub description: Option<String>,
    /// Schema of the tool's parameters - usually a JSON schema
    pub parameters_schema: String,
}

/// Describes a tool call request
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ToolCall {
    /// Call identifier
    pub id: String,
    /// Name of the tool
    pub name: String,
    /// Arguments of the tool call
    pub arguments_json: String,
}

/// Describes a successful tool call
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ToolSuccess {
    /// Call identifier
    pub id: String,
    /// Name of the tool
    pub name: String,
    /// Result of the tool call in JSON
    pub result_json: String,
    /// Execution time of the tool call in milliseconds
    pub execution_time_ms: Option<u32>,
}

/// Describes a failed tool call
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ToolFailure {
    /// Call identifier
    pub id: String,
    /// Name of the tool
    pub name: String,
    /// Error message of the tool call
    pub error_message: String,
    /// Error code of the tool call
    pub error_code: Option<String>,
}

/// Result of a tool call
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub enum ToolResult {
    /// The tool call succeeded
    Success(ToolSuccess),
    /// The tool call failed
    Error(ToolFailure),
}

/// Simple key-value pair
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Kv {
    pub key: String,
    pub value: String,
}

/// LLM configuration
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Config {
    /// The model to use
    pub model: String,
    /// Temperature
    pub temperature: Option<f32>,
    /// Maximum number of tokens
    pub max_tokens: Option<u32>,
    /// A sequence where the model stops generating tokens
    pub stop_sequences: Option<Vec<String>>,
    /// List of available tools
    pub tools: Option<Vec<ToolDefinition>>,
    /// Tool choice policy
    pub tool_choice: Option<String>,
    /// Additional LLM provider specific key-value pairs
    pub provider_options: Option<Vec<Kv>>,
}

/// Token usage statistics
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Usage {
    /// Number of input tokens used
    pub input_tokens: Option<u32>,
    /// Number of output tokens generated
    pub output_tokens: Option<u32>,
    /// Total number of tokens used
    pub total_tokens: Option<u32>,
}

/// Metadata about an LLM response
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct ResponseMetadata {
    /// Reason for finishing the conversation
    pub finish_reason: Option<FinishReason>,
    /// Usage statistics
    pub usage: Option<Usage>,
    /// Provider-specific ID
    pub provider_id: Option<String>,
    /// Timestamp
    pub timestamp: Option<String>,
    /// Provider-specific additional metadata in JSON
    pub provider_metadata_json: Option<String>,
}

/// LLM error
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Error {
    /// Error code
    pub code: ErrorCode,
    /// Error message
    pub message: String,
    /// More details in JSON, in a provider-specific format
    pub provider_error_json: Option<String>,
}

/// Response from an LLM
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct Response {
    /// Response ID
    pub id: String,
    /// Result contents
    pub content: Vec<ContentPart>,
    /// Tool call requests
    pub tool_calls: Vec<ToolCall>,
    /// Response metadata
    pub metadata: ResponseMetadata,
}

/// Chat events that can happen during a chat session
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub enum Event {
    /// Message asked by the user
    Message(Message),
    /// Response from the LLM
    Response(Response),
    /// Provided tool results
    ToolResults(Vec<ToolResult>),
}

/// Changes in a streaming conversation
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub struct StreamDelta {
    /// New content parts
    pub content: Option<Vec<ContentPart>>,
    /// New tool calls
    pub tool_calls: Option<Vec<ToolCall>>,
}

/// Event in a streaming conversation
#[derive(Clone, Debug, PartialEq, golem_rust::FromValueAndType, golem_rust::IntoValue)]
pub enum StreamEvent {
    /// New incoming response content or tool call requests
    Delta(StreamDelta),
    /// Conversation finished
    Finish(ResponseMetadata),
}

/// Represents an ongoing streaming LLM conversation
pub struct ChatStream {
    inner: Box<dyn ChatStreamInterface>,
}

impl ChatStream {
    pub fn new<T: ChatStreamInterface>(val: T) -> Self {
        Self {
            inner: Box::new(val),
        }
    }

    pub fn get<T: ChatStreamInterface>(&self) -> &T {
        self.inner
            .as_any()
            .downcast_ref::<T>()
            .expect("ChatStream type mismatch")
    }

    pub fn get_mut<T: ChatStreamInterface>(&mut self) -> &mut T {
        self.inner
            .as_any_mut()
            .downcast_mut::<T>()
            .expect("ChatStream type mismatch")
    }
}

impl std::ops::Deref for ChatStream {
    type Target = dyn ChatStreamInterface;

    fn deref(&self) -> &Self::Target {
        &*self.inner
    }
}

impl std::ops::DerefMut for ChatStream {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut *self.inner
    }
}
