[package]
name = "websearch-tavily"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:websearch-tavily"

[package.metadata.component.dependencies]
