[package]
name = "exec-javascript"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.16"
anyhow = "1.0"
shared = { path = "../shared" }

[package.metadata.component]
package = "golem:exec"

[package.metadata.component.target]
path = "../wit"