// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:stt/vocabularies@1.0.0" = "golem_stt::golem::stt::vocabularies"
//   * with "golem:stt/languages@1.0.0" = "golem_stt::golem::stt::languages"
//   * with "golem:stt/types@1.0.0" = "golem_stt::golem::stt::types"
//   * with "golem:stt/transcription@1.0.0" = "golem_stt::golem::stt::transcription"
//   * generate_unused_types
use golem_stt::golem::stt::types as __with_name0;
use golem_stt::golem::stt::vocabularies as __with_name1;
use golem_stt::golem::stt::languages as __with_name2;
use golem_stt::golem::stt::transcription as __with_name3;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:golem:stt-deepgram@1.0.0:stt-library:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2158] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xec\x0f\x01A\x02\x01\
A\x0e\x01B\x1e\x01m\x03\x07seconds\x08requests\x07credits\x04\0\x0aquota-unit\x03\
\0\0\x01r\x04\x04usedy\x05limity\x0areset-timew\x04unit\x01\x04\0\x0aquota-info\x03\
\0\x02\x01q\x0d\x0dinvalid-audio\x01s\0\x12unsupported-format\x01s\0\x14unsuppor\
ted-language\x01s\0\x14transcription-failed\x01s\0\x0cunauthorized\x01s\0\x0dacc\
ess-denied\x01s\0\x0equota-exceeded\x01\x03\0\x0crate-limited\x01y\0\x14insuffic\
ient-credits\0\0\x15unsupported-operation\x01s\0\x13service-unavailable\x01s\0\x0d\
network-error\x01s\0\x0einternal-error\x01s\0\x04\0\x09stt-error\x03\0\x04\x01s\x04\
\0\x0dlanguage-code\x03\0\x06\x01m\x06\x03wav\x03mp3\x04flac\x03ogg\x03aac\x03pc\
m\x04\0\x0caudio-format\x03\0\x08\x01ky\x01k}\x01r\x03\x06format\x09\x0bsample-r\
ate\x0a\x08channels\x0b\x04\0\x0caudio-config\x03\0\x0c\x01m\x01\x04word\x04\0\x10\
timing-mark-type\x03\0\x0e\x01kv\x01r\x03\x12start-time-secondsv\x10end-time-sec\
onds\x10\x09mark-type\x0f\x04\0\x0btiming-info\x03\0\x11\x01ks\x01r\x05\x04texts\
\x0astart-timev\x08end-timev\x0aconfidence\x10\x0aspeaker-id\x13\x04\0\x0cword-s\
egment\x03\0\x14\x01p\x15\x01r\x03\x04texts\x0aconfidencev\x05words\x16\x04\0\x16\
transcript-alternative\x03\0\x17\x01r\x05\x10duration-secondsv\x10audio-size-byt\
esy\x0arequest-ids\x05model\x13\x08language\x07\x04\0\x16transcription-metadata\x03\
\0\x19\x01p\x18\x01r\x02\x0calternatives\x1b\x08metadata\x1a\x04\0\x14transcript\
ion-result\x03\0\x1c\x04\0\x15golem:stt/types@1.0.0\x05\0\x02\x03\0\0\x09stt-err\
or\x01B\x10\x02\x03\x02\x01\x01\x04\0\x09stt-error\x03\0\0\x04\0\x0avocabulary\x03\
\x01\x01h\x02\x01@\x01\x04self\x03\0s\x04\0\x1b[method]vocabulary.get-name\x01\x04\
\x01ps\x01@\x01\x04self\x03\0\x05\x04\0\x1e[method]vocabulary.get-phrases\x01\x06\
\x01j\0\x01\x01\x01@\x01\x04self\x03\0\x07\x04\0\x19[method]vocabulary.delete\x01\
\x08\x01i\x02\x01j\x01\x09\x01\x01\x01@\x02\x04names\x07phrases\x05\0\x0a\x04\0\x11\
create-vocabulary\x01\x0b\x04\0\x1cgolem:stt/vocabularies@1.0.0\x05\x02\x02\x03\0\
\0\x0dlanguage-code\x01B\x0a\x02\x03\x02\x01\x03\x04\0\x0dlanguage-code\x03\0\0\x02\
\x03\x02\x01\x01\x04\0\x09stt-error\x03\0\x02\x01r\x03\x04code\x01\x04names\x0bn\
ative-names\x04\0\x0dlanguage-info\x03\0\x04\x01p\x05\x01j\x01\x06\x01\x03\x01@\0\
\0\x07\x04\0\x0elist-languages\x01\x08\x04\0\x19golem:stt/languages@1.0.0\x05\x04\
\x02\x03\0\0\x0caudio-config\x02\x03\0\0\x14transcription-result\x02\x03\0\0\x16\
transcript-alternative\x02\x03\0\x01\x0avocabulary\x01B\x1f\x02\x03\x02\x01\x05\x04\
\0\x0caudio-config\x03\0\0\x02\x03\x02\x01\x06\x04\0\x14transcription-result\x03\
\0\x02\x02\x03\x02\x01\x01\x04\0\x09stt-error\x03\0\x04\x02\x03\x02\x01\x03\x04\0\
\x0dlanguage-code\x03\0\x06\x02\x03\x02\x01\x07\x04\0\x16transcript-alternative\x03\
\0\x08\x02\x03\x02\x01\x08\x04\0\x0avocabulary\x03\0\x0a\x01k\x7f\x01k\x07\x01ks\
\x01ps\x01k\x0f\x01r\x08\x11enable-timestamps\x0c\x1aenable-speaker-diarization\x0c\
\x08language\x0d\x05model\x0e\x10profanity-filter\x0c\x0espeech-context\x10\x16e\
nable-word-confidence\x0c\x14enable-timing-detail\x0c\x04\0\x12transcribe-option\
s\x03\0\x11\x01p}\x01k\x12\x01r\x03\x05audio\x13\x06config\x01\x07options\x14\x04\
\0\x12transcribe-request\x03\0\x15\x01j\x01\x03\x01\x05\x01@\x03\x05audio\x13\x06\
config\x01\x07options\x14\0\x17\x04\0\x0atranscribe\x01\x18\x01p\x16\x01p\x03\x01\
j\x01\x1a\x01\x05\x01@\x01\x08requests\x19\0\x1b\x04\0\x10multi-transcribe\x01\x1c\
\x04\0\x1dgolem:stt/transcription@1.0.0\x05\x09\x04\0$golem:stt-deepgram/stt-lib\
rary@1.0.0\x04\0\x0b\x11\x01\0\x0bstt-library\x03\0\0\0G\x09producers\x01\x0cpro\
cessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
