[package]
name = "golem-vector"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem-llm"
description = "WebAssembly components for working with Vector Database APIs, with special support for Golem Cloud"

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
golem-rust = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
thiserror = "2.0.12"
wasi-logger = "0.1.2"
<<<<<<< HEAD
wit-bindgen = { workspace = true }
=======
wit-bindgen = { version = "0.43.0" }
>>>>>>> a6364a7537634b59f83c3bc53e389acf5dd86b49
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
durability = ["golem-rust/durability"]

[lints.rust]
dead_code = "allow"
