// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:video/video@1.0.0" = "golem_video::golem::video::video"
//   * generate_unused_types
use golem_video::golem::video::video as __with_name0;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:golem:video-stability@1.0.0:video-library:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1180] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x98\x08\x01A\x02\x01\
A\x02\x01B5\x01q\x06\x0dinvalid-input\x01s\0\x13unsupported-feature\x01s\0\x0equ\
ota-exceeded\0\0\x11generation-failed\x01s\0\x09cancelled\0\0\x0einternal-error\x01\
s\0\x04\0\x0bvideo-error\x03\0\0\x01m\x02\x05first\x04last\x04\0\x0aimage-role\x03\
\0\x02\x01p}\x01q\x02\x03url\x01s\0\x05bytes\x01\x04\0\x04\0\x0amedia-data\x03\0\
\x05\x01r\x01\x04data\x06\x04\0\x0binput-image\x03\0\x07\x01ks\x01k\x03\x01r\x03\
\x04data\x08\x06prompt\x09\x04role\x0a\x04\0\x09reference\x03\0\x0b\x01q\x02\x04\
text\x01s\0\x05image\x01\x0c\0\x04\0\x0bmedia-input\x03\0\x0d\x01r\x01\x04data\x06\
\x04\0\x0abase-video\x03\0\x0f\x01r\x01\x04data\x06\x04\0\x09narration\x03\0\x11\
\x01m\x04\x06square\x08portrait\x09landscape\x06cinema\x04\0\x0caspect-ratio\x03\
\0\x13\x01m\x04\x02sd\x02hd\x03fhd\x03uhd\x04\0\x0aresolution\x03\0\x15\x01r\x02\
\x03keys\x05values\x04\0\x02kv\x03\0\x17\x01kw\x01kv\x01k\x14\x01k\x16\x01k\x7f\x01\
p\x18\x01k\x08\x01r\x0c\x0fnegative-prompt\x09\x04seed\x19\x09scheduler\x09\x0eg\
uidance-scale\x1a\x0caspect-ratio\x1b\x10duration-seconds\x1a\x0aresolution\x1c\x05\
model\x09\x0cenable-audio\x1d\x0eenhance-prompt\x1d\x10provider-options\x1e\x09l\
astframe\x1f\x04\0\x11generation-config\x03\0\x20\x01k\x04\x01ky\x01r\x07\x03uri\
\x09\x0cbase64-bytes\"\x09mime-types\x05width#\x06height#\x03fps\x1a\x10duration\
-seconds\x1a\x04\0\x05video\x03\0$\x01q\x04\x07pending\0\0\x07running\0\0\x09suc\
ceeded\0\0\x06failed\x01s\0\x04\0\x0ajob-status\x03\0&\x01p%\x01k(\x01k\x1e\x01r\
\x03\x06status'\x06videos)\x08metadata*\x04\0\x0cvideo-result\x03\0+\x01j\x01s\x01\
\x01\x01@\x02\x05input\x0e\x06config!\0-\x04\0\x08generate\x01.\x01j\x01,\x01\x01\
\x01@\x01\x06job-ids\0/\x04\0\x04poll\x010\x01@\x01\x06job-ids\0-\x04\0\x06cance\
l\x011\x04\0\x17golem:video/video@1.0.0\x05\0\x04\0)golem:video-stability/video-\
library@1.0.0\x04\0\x0b\x13\x01\0\x0dvideo-library\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
