[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-veo",
    "build-stability",
    "build-kling",
    "build-runway",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-veo",
    "release-build-stability",
    "release-build-kling",
    "release-build-runway",
] }

[tasks.build-veo]
command = "cargo"
args = ["build", "-p", "golem-ai-video-veo"]

[tasks.build-stability]
command = "cargo"
args = ["build", "-p", "golem-ai-video-stability"]

[tasks.build-kling]
command = "cargo"
args = ["build", "-p", "golem-ai-video-kling"]

[tasks.build-runway]
command = "cargo"
args = ["build", "-p", "golem-ai-video-runway"]

[tasks.release-build-veo]
command = "cargo"
args = ["build", "-p", "golem-ai-video-veo", "--release"]

[tasks.release-build-stability]
command = "cargo"
args = ["build", "-p", "golem-ai-video-stability", "--release"]

[tasks.release-build-kling]
command = "cargo"
args = ["build", "-p", "golem-ai-video-kling", "--release"]

[tasks.release-build-runway]
command = "cargo"
args = ["build", "-p", "golem-ai-video-runway", "--release"]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds video test components with golem-cli"
script = '''
cd ../test/video

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset veo-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset stability-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset kling-debug
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset runway-debug

cd ../video-advanced

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset kling-debug
golem-cli --dev-mode clean
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds video test components with golem-cli"
script = '''
cd ../test/video

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset veo-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset stability-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset kling-release
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset runway-release

cd ../video-advanced

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset kling-release
golem-cli --dev-mode clean
'''