//! TTS-ElevenLabs WASM Component
//!
//! Implements the golem:tts@1.0.0 WIT interface for ElevenLabs text-to-speech provider.
//!
//! ## Standard Compliance
//! - C1 (Totality): All functions have explicit returns.
//! - C2 (Explicitness): Explicit imports, no star imports, no unwrap().
//! - C3 (Determinism): External API calls wrapped in atomic operations.
//! - C4 (Local Reasoning): Explicit control flow, clear data ownership.
//! - C5 (Failure as Value): Comprehensive TtsError mapping.

// These bindings are generated by cargo-component/wit-bindgen
#[allow(warnings)]
mod bindings;

// Re-export bindings for sub-module access
pub use bindings::exports::golem::tts::advanced as wit_advanced;
pub use bindings::exports::golem::tts::streaming as wit_streaming;
pub use bindings::exports::golem::tts::synthesis as wit_synthesis;
pub use bindings::exports::golem::tts::types as wit_types;
pub use bindings::exports::golem::tts::voices as wit_voices;

// Internal module declarations
mod advanced;
mod client;
mod streaming;
mod synthesis;
mod types;
mod voices;

use wit_advanced::Guest as AdvancedGuest;
use wit_streaming::Guest as StreamingGuest;
use wit_synthesis::Guest as SynthesisGuest;
use wit_voices::Guest as VoicesGuest;

/// Main component implementation
struct TtsElevenlabsComponent;

// ============================================================
// VOICES INTERFACE IMPLEMENTATION
// ============================================================

impl VoicesGuest for TtsElevenlabsComponent {
    type Voice = voices::VoiceImpl;
    type VoiceResults = voices::VoiceResultsImpl;

    fn list_voices(
        filter: Option<wit_voices::VoiceFilter>,
    ) -> Result<wit_voices::VoiceResults, wit_types::TtsError> {
        return voices::list_voices(filter);
    }

    fn get_voice(voice_id: String) -> Result<wit_voices::Voice, wit_types::TtsError> {
        return voices::get_voice(voice_id);
    }

    fn search_voices(
        query: String,
        filter: Option<wit_voices::VoiceFilter>,
    ) -> Result<Vec<wit_voices::VoiceInfo>, wit_types::TtsError> {
        return voices::search_voices(query, filter);
    }

    fn list_languages() -> Result<Vec<wit_voices::LanguageInfo>, wit_types::TtsError> {
        return voices::list_languages();
    }
}

// ============================================================
// SYNTHESIS INTERFACE IMPLEMENTATION
// ============================================================

impl SynthesisGuest for TtsElevenlabsComponent {
    fn synthesize(
        input: wit_types::TextInput,
        voice: wit_voices::VoiceBorrow<'_>,
        options: Option<wit_synthesis::SynthesisOptions>,
    ) -> Result<wit_types::SynthesisResult, wit_types::TtsError> {
        return synthesis::synthesize(input, voice.get(), options);
    }

    fn synthesize_batch(
        inputs: Vec<wit_types::TextInput>,
        voice: wit_voices::VoiceBorrow<'_>,
        options: Option<wit_synthesis::SynthesisOptions>,
    ) -> Result<Vec<wit_types::SynthesisResult>, wit_types::TtsError> {
        return synthesis::synthesize_batch(inputs, voice.get(), options);
    }

    fn get_timing_marks(
        input: wit_types::TextInput,
        voice: wit_voices::VoiceBorrow<'_>,
    ) -> Result<Vec<wit_types::TimingInfo>, wit_types::TtsError> {
        return synthesis::get_timing_marks(input, voice.get());
    }

    fn validate_input(
        input: wit_types::TextInput,
        voice: wit_voices::VoiceBorrow<'_>,
    ) -> Result<wit_synthesis::ValidationResult, wit_types::TtsError> {
        return synthesis::validate_input(input, voice.get());
    }
}

// ============================================================
// STREAMING INTERFACE IMPLEMENTATION
// ============================================================

impl StreamingGuest for TtsElevenlabsComponent {
    type SynthesisStream = streaming::SynthesisStreamImpl;
    type VoiceConversionStream = streaming::VoiceConversionStreamImpl;

    fn create_stream(
        voice: wit_voices::VoiceBorrow<'_>,
        options: Option<wit_synthesis::SynthesisOptions>,
    ) -> Result<wit_streaming::SynthesisStream, wit_types::TtsError> {
        return streaming::create_stream(voice.get(), options);
    }

    fn create_voice_conversion_stream(
        target_voice: wit_voices::VoiceBorrow<'_>,
        options: Option<wit_synthesis::SynthesisOptions>,
    ) -> Result<wit_streaming::VoiceConversionStream, wit_types::TtsError> {
        return streaming::create_voice_conversion_stream(target_voice.get(), options);
    }
}

// ============================================================
// ADVANCED INTERFACE IMPLEMENTATION
// ============================================================

impl AdvancedGuest for TtsElevenlabsComponent {
    type PronunciationLexicon = advanced::PronunciationLexiconImpl;
    type LongFormOperation = advanced::LongFormOperationImpl;

    fn create_voice_clone(
        name: String,
        audio_samples: Vec<wit_advanced::AudioSample>,
        description: Option<String>,
    ) -> Result<wit_voices::Voice, wit_types::TtsError> {
        return advanced::create_voice_clone(name, audio_samples, description);
    }

    fn design_voice(
        name: String,
        characteristics: wit_advanced::VoiceDesignParams,
    ) -> Result<wit_voices::Voice, wit_types::TtsError> {
        return advanced::design_voice(name, characteristics);
    }

    fn convert_voice(
        input_audio: Vec<u8>,
        target_voice: wit_voices::VoiceBorrow<'_>,
        preserve_timing: Option<bool>,
    ) -> Result<Vec<u8>, wit_types::TtsError> {
        return advanced::convert_voice(input_audio, target_voice.get(), preserve_timing);
    }

    fn generate_sound_effect(
        description: String,
        duration_seconds: Option<f32>,
        style_influence: Option<f32>,
    ) -> Result<Vec<u8>, wit_types::TtsError> {
        return advanced::generate_sound_effect(description, duration_seconds, style_influence);
    }

    fn create_lexicon(
        name: String,
        language: String,
        entries: Option<Vec<wit_advanced::PronunciationEntry>>,
    ) -> Result<wit_advanced::PronunciationLexicon, wit_types::TtsError> {
        return advanced::create_lexicon(name, language, entries);
    }

    fn synthesize_long_form(
        content: String,
        voice: wit_voices::VoiceBorrow<'_>,
        output_location: String,
        chapter_breaks: Option<Vec<u32>>,
    ) -> Result<wit_advanced::LongFormOperation, wit_types::TtsError> {
        return advanced::synthesize_long_form(
            content,
            voice.get(),
            output_location,
            chapter_breaks,
        );
    }
}

// Export the component using the generated macro
bindings::export!(TtsElevenlabsComponent with_types_in bindings);
