[package]
name = "golem-vector-pgvector"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem-llm"
description = "WebAssembly component for pgvector (PostgreSQL) vector search, with Golem Cloud"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
# pgvector requires database connectivity; keep durability optional
default = ["durability"]
durability = ["golem-rust/durability", "golem-vector/durability"]

[dependencies]
golem-vector = { path = "../vector", version = "0.0.0", default-features = false }
log = { workspace = true }
golem-rust = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wit-bindgen-rt = { workspace = true }
postgres = { version = "0.19.7", default-features = false, features = ["with-uuid-1", "with-serde_json-1"] }
base64 = { workspace = true }
r2d2_postgres = { version = "0.18" }

[package.metadata.component]
package = "golem:vector-pgvector"

[package.metadata.component.bindings]
# No bindings generated yet – will be enabled later.
generate_unused_types = true

[package.metadata.component.bindings.with]
"golem:vector/types@1.0.0" = "golem_vector::golem::vector::types"
"golem:vector/collections@1.0.0" = "golem_vector::golem::vector::collections"
"golem:vector/vectors@1.0.0" = "golem_vector::golem::vector::vectors"
"golem:vector/search@1.0.0" = "golem_vector::golem::vector::search"
"golem:vector/search-extended@1.0.0" = "golem_vector::golem::vector::search_extended"
"golem:vector/namespaces@1.0.0" = "golem_vector::golem::vector::namespaces"
"golem:vector/connection@1.0.0" = "golem_vector::golem::vector::connection"

[package.metadata.component.target]
path = "../wit"
