# yaml-language-server: $schema=https://json.schemastore.org/cargo-make
[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-aws",
    "build-azure",
    "build-deepgram",
    "build-google",
    "build-whisper",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-aws",
    "release-build-azure",
    "release-build-deepgram",
    "release-build-google",
    "release-build-whisper",
] }

[tasks.build-aws]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-aws"]

[tasks.build-azure]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-azure"]

[tasks.build-deepgram]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-deepgram"]

[tasks.build-google]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-google"]

[tasks.build-whisper]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-whisper"]

[tasks.release-build-aws]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-aws", "--release"]

[tasks.release-build-azure]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-azure", "--release"]

[tasks.release-build-deepgram]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-deepgram", "--release"]

[tasks.release-build-google]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-google", "--release"]

[tasks.release-build-whisper]
command = "cargo"
args = ["build", "-p", "golem-ai-stt-whisper", "--release"]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds stt test components with golem-cli"
script = '''
cd ../test/stt

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset aws-debug
golem-cli --dev-mode build --preset azure-debug
golem-cli --dev-mode build --preset deepgram-debug
golem-cli --dev-mode build --preset google-debug
golem-cli --dev-mode build --preset whisper-debug
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds stt test components with golem-cli"
script = '''
cd ../test/stt

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset aws-release
golem-cli --dev-mode build --preset azure-release
golem-cli --dev-mode build --preset deepgram-release
golem-cli --dev-mode build --preset google-release
golem-cli --dev-mode build --preset whisper-release
'''