# yaml-language-server: $schema=https://json.schemastore.org/cargo-make
[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-aws",
    "build-azure",
    "build-deepgram",
    "build-google",
    "build-whisper",
] }

[tasks.build-portable]
run_task = { name = [
    "build-aws-portable",
    "build-azure-portable",
    "build-deepgram-portable",
    "build-google-portable",
    "build-whisper-portable",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-aws",
    "release-build-azure",
    "release-build-deepgram",
    "release-build-google",
    "release-build-whisper",
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-aws-portable",
    "release-build-azure-portable",
    "release-build-deepgram-portable",
    "release-build-google-portable",
    "release-build-whisper-portable",
] }

[tasks.build-aws]
command = "cargo"
args = ["build", "-p", "golem-stt-aws"]

[tasks.build-aws-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-aws", "--no-default-features"]

[tasks.build-azure]
command = "cargo"
args = ["build", "-p", "golem-stt-azure"]

[tasks.build-azure-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-azure", "--no-default-features"]

[tasks.build-deepgram]
command = "cargo"
args = ["build", "-p", "golem-stt-deepgram"]

[tasks.build-deepgram-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-deepgram", "--no-default-features"]

[tasks.build-google]
command = "cargo"
args = ["build", "-p", "golem-stt-google"]


[tasks.build-google-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-google", "--no-default-features"]


[tasks.build-whisper]
command = "cargo"
args = ["build", "-p", "golem-stt-whisper"]

[tasks.build-whisper-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-whisper", "--no-default-features"]

[tasks.release-build-aws]
command = "cargo"
args = ["build", "-p", "golem-stt-aws", "--release"]

[tasks.release-build-aws-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-aws", "--release", "--no-default-features"]

[tasks.release-build-azure]
command = "cargo"
args = ["build", "-p", "golem-stt-azure", "--release"]

[tasks.release-build-azure-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-azure", "--release", "--no-default-features"]

[tasks.release-build-deepgram]
command = "cargo"
args = ["build", "-p", "golem-stt-deepgram", "--release"]

[tasks.release-build-deepgram-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-stt-deepgram",
    "--release",
    "--no-default-features",
]

[tasks.release-build-google]
command = "cargo"
args = ["build", "-p", "golem-stt-google", "--release"]

[tasks.release-build-google-portable]
command = "cargo"
args = ["build", "-p", "golem-stt-google", "--release", "--no-default-features"]

[tasks.release-build-whisper]
command = "cargo"
args = ["build", "-p", "golem-stt-whisper", "--release"]

[tasks.release-build-whisper-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-stt-whisper",
    "--release",
    "--no-default-features",
]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds stt test components with golem-cli"
script = '''
cd ../test/stt

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset aws-debug
golem-cli --dev-mode build --preset azure-debug
golem-cli --dev-mode build --preset deepgram-debug
golem-cli --dev-mode build --preset google-debug
golem-cli --dev-mode build --preset whisper-debug
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds stt test components with golem-cli"
script = '''
cd ../test/stt

golem-cli --version
golem-cli --dev-mode clean
golem-cli --dev-mode build --preset aws-release
golem-cli --dev-mode build --preset azure-release
golem-cli --dev-mode build --preset deepgram-release
golem-cli --dev-mode build --preset google-release
golem-cli --dev-mode build --preset whisper-release
'''
