[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-milvus",
    "build-pgvector",
    "build-pinecone",
    "build-qdrant"
] }

[tasks.build-portable]
run_task = { name = [
    "build-milvus-portable",
    "build-pgvector-portable",
    "build-pinecone-portable",
    "build-qdrant-portable"
] }

[tasks.release-build]
run_task = { name = [
    "release-build-milvus",
    "release-build-pinecone",
    "release-build-pgvector",
    "release-build-qdrant"
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-milvus-portable",
    "release-build-pgvector-portable",
    "release-build-pinecone-portable",
    "release-build-qdrant-portable"
] }

[tasks.build-milvus]
command = "cargo"
args = ["build", "-p", "golem-vector-milvus"]

[tasks.build-milvus-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-milvus", "--no-default-features"]


[tasks.build-pgvector]
command = "cargo"
args = ["build", "-p", "golem-vector-pgvector"]

[tasks.build-pgvector-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-pgvector", "--no-default-features"]


[tasks.build-pinecone]
command = "cargo"
args = ["build", "-p", "golem-vector-pinecone"]

[tasks.build-pinecone-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-pinecone", "--no-default-features"]

[tasks.build-qdrant]
command = "cargo"
args = ["build", "-p", "golem-vector-qdrant"]

[tasks.build-qdrant-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-qdrant", "--no-default-features"]


[tasks.release-build-milvus]
command = "cargo"
args = ["build", "-p", "golem-vector-milvus", "--release"]

[tasks.release-build-milvus-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-milvus", "--release", "--no-default-features"]


[tasks.release-build-pgvector]
command = "cargo"
args = ["build", "-p", "golem-vector-pgvector", "--release"]

[tasks.release-build-pgvector-portable]
command = "cargo"
args = [
    "build",
    "-p",
    "golem-vector-pgvector",
    "--release",
    "--no-default-features",
]


[tasks.release-build-pinecone]
command = "cargo"
args = ["build", "-p", "golem-vector-pinecone", "--release"]

[tasks.release-build-pinecone-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-pinecone", "--release", "--no-default-features"]

[tasks.release-build-qdrant]
command = "cargo"
args = ["build", "-p", "golem-vector-qdrant", "--release"]

[tasks.release-build-qdrant-portable]
command = "cargo"
args = ["build", "-p", "golem-vector-qdrant", "--release", "--no-default-features"]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds vector test components with golem-cli"
script = '''
cd ../test/vector

golem-cli --version
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b milvus-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pgvector-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pinecone-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b qdrant-debug
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds vector test components with golem-cli"
script = '''
cd ../test/vector

golem-cli --version
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b milvus-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pgvector-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pinecone-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b qdrant-release
'''
