[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-milvus",
    "build-pgvector",
    "build-pinecone",
    "build-qdrant"
] }

[tasks.release-build]
run_task = { name = [
    "release-build-milvus",
    "release-build-pinecone",
    "release-build-pgvector",
    "release-build-qdrant"
] }

[tasks.build-milvus]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-milvus"]

[tasks.build-pgvector]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-pgvector"]

[tasks.build-pinecone]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-pinecone"]

[tasks.build-qdrant]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-qdrant"]

[tasks.release-build-milvus]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-milvus", "--release"]

[tasks.release-build-pgvector]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-pgvector", "--release"]

[tasks.release-build-pinecone]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-pinecone", "--release"]

[tasks.release-build-qdrant]
command = "cargo"
args = ["build", "-p", "golem-ai-vector-qdrant", "--release"]

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds vector test components with golem-cli"
script = '''
cd ../test/vector

golem-cli --version
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b milvus-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pgvector-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pinecone-debug
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b qdrant-debug
'''

[tasks.release-build-test-components]
dependencies = ["release-build"]
description = "Builds vector test components with golem-cli"
script = '''
cd ../test/vector

golem-cli --version
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b milvus-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pgvector-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b pinecone-release
golem-cli --dev-mode app clean
golem-cli --dev-mode app build -b qdrant-release
'''
