[package]
name = "exec-python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.16"

[package.metadata.component]
package = "golem:exec"

[package.metadata.component.target]
path = "../wit"